name: First workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Hello
      run: echo Hello there!!!
    - name: Show Java Version
      run: java -version
    - name: Show directory name
      run: pwd
    - name: Show directory content
      run: ls
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Gradle Init
      run: demo-ci/gradlew init
    - name: Gradle Tasks
      run: demo-ci/gradlew tasks
    - name: Gradle Build
      run: demo-ci/gradlew build
    - name: Gradle Tasks
      run: demo-ci/gradlew tasks
