name: First workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Normal command line statements
      run: |
        echo Hello there!!!
        pwd
        ls
        java -version
        chmod +x gradlew
        ./gradlew --version
    - name: Gradle Build (Assemble + Test)
      run: |
        chmod +x gradlew
        ./gradlew build
