name: First workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Gradle Build
      run: ./gradlew build
    - name: Gradle Test
      run:  ./gradlew test
