name: First workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Hello
      run: echo Hello there!!!
    - name: Show Java Version
      run: java -version
    - name: Show directory name
      run: pwd
    - name: Show directory content
      run: ls
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build
